recipe: default.v1
language: hr
assistant_id: tempered-condensation
pipeline:
- name: CompactLLMCommandGenerator
  llm:
    model_group: llama_3_1_8b_model
  flow_retrieval:
    active: false
policies:
- name: FlowPolicy